name: Update badges

# Controls when the workflow will run
on:
  #schedule:
      # run at first day of week:
  #    - cron:  '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./js

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      # setup node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      
      # run getbadges
      - name: build
        run: node get_badges.js
        
      # push changes:
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ../badges/
          git commit -a -m "Add changes"
        
      # push badges to repo
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
