name: Update badges

# Controls when the workflow will run
on:
  #schedule:
      # run at first day of week:
  #    - cron:  '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      # cwd to js
      - run: |
          cd js
      
      # setup node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      
      # run getbadges
      - name: build
        run: node getbadges.js